---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Remove html directory
  ansible.builtin.file:
    path: /var/www/html
    state: absent

- name: Disable default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove html directory
  ansible.builtin.file:
    path: /var/www/html
    state: absent
