---
- name: Update apt
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
    state: latest

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes
